DROP TABLE IF EXISTS MOVIE; 
CREATE TABLE MOVIE (  
id INT AUTO_INCREMENT  PRIMARY KEY,  
title VARCHAR NOT NULL,  
releaseDate VARCHAR NOT NULL,
showCycle VARCHAR
); 

DROP TABLE IF EXISTS SCREEN;  
CREATE TABLE SCREEN (  
id INT AUTO_INCREMENT  PRIMARY KEY,  
screenType VARCHAR NOT NULL,
movieId INT NOT NULL,
foreign key (movieId) references MOVIE(id)
);

DROP TABLE IF EXISTS CINEMA;  
CREATE TABLE CINEMA (  
id INT AUTO_INCREMENT  PRIMARY KEY,  
screenType VARCHAR NOT NULL,
screenId INT NOT NULL,
foreign key (screenId) references SCREEN(id)
); 

DROP TABLE IF EXISTS APPUSER;  
CREATE TABLE APPUSER (  
id INT AUTO_INCREMENT  PRIMARY KEY,  
username VARCHAR NOT NULL,  
password VARCHAR NOT NULL
);  

DROP TABLE IF EXISTS USER_CINEMA_MAP;  
CREATE TABLE USER_CINEMA_MAP (  
id INT AUTO_INCREMENT  PRIMARY KEY,  
cinemaId INT NOT NULL,
userId INT NOT NULL,
movieDate VARCHAR NOT NULL,  
movieTime VARCHAR NOT NULL
);